### ISSUE TITLE
Issue with the background of both timers

### ISSUE THREAD

**Issue by ghost** [Litzuck/lol-spectator-overlay-client#3] opened 2021-03-28 03:54 UTC
What happens is that at the end of all the picks and bans, when there are 60 seconds left for the game to start, "Picking Phase 2" continues to appear in the middle of both timers with the color red in the background, and both timers still have the red color in the background.
The correct thing is that the background of both timers should turn black and the text "Picking Phase 2" should disappear along with the red background of the same.

I am going to put 2 images of what happens and how it should be correctly.
![1](https://user-images.githubusercontent.com/81208305/112741912-12349380-8f60-11eb-8ee1-e7d956a31be1.png)
![2](https://user-images.githubusercontent.com/81208305/112741915-16f94780-8f60-11eb-8e83-80e8a5e57b7b.png)

**Comment by Litzuck** [comment] 2021-03-29 15:30
Thanks for pointing this out. It should have been fixed in the last release, but I'll look into it.

**Comment by ghost** [comment] 2021-03-29 15:33
> Thanks for pointing this out. It should have been fixed in the last release, but I'll look into it.

Ok thanks!

**Comment by Litzuck** [comment] 2021-03-29 16:00
I wasn't able to replicate this bug with on my side. Could you please send me the log file of the champion select, which caused this issue.  It can be found in the `logs` folder and is named `replay_TIMESTAMP.json`.

**Comment by ghost** [comment] 2021-03-29 17:25
> I wasn't able to replicate this bug with on my side. Could you please send me the log file of the champion select, which caused this issue. It can be found in the `logs` folder and is named `replay_TIMESTAMP.json`.

Github doesn't allow me to upload these types of files, do you have discord or something to talk about and send the file easier?

**Comment by Litzuck** [comment] 2021-03-29 20:11
Yes you can add me on Discord: Litzuck#5760.

**Comment by Litzuck** [comment] 2021-03-30 15:55
Problem solved. Currenty intended behavior if lobby is not full.
Closing issue.

**Closed as completed by Litzuck** 2021-03-30 15:55 UTC
