### ISSUE TITLE
Ban display error

### ISSUE THREAD

**Issue by Sky-CSC** [Litzuck/lol-spectator-overlay-client#16] opened 2021-06-14 19:09 UTC
Hi, 
I think is a bug with BOT.
When I start ban with blue side in custom game, the first ban isn't take into consideration.
(When I'm solo in custom game it works normally)
(I download the last release but the bug persist)

https://user-images.githubusercontent.com/46931832/121945869-8d823600-cd54-11eb-8df7-65fc4e0e3e9c.mp4

**Comment by Litzuck** [comment] 2021-06-28 19:03
Sorry for taking so long to answer, I was quite busy in the last weeks. Yes that is a current bug, which occurs when there are bots in the lobby. I wasn't able to pinpoint the cause of it and it is currently out of scope and not to be expected to be fixed soon.

**Closed as completed** 2022-05-03 22:54 UTC
